service: servicio-vuelos-compras

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    COMPRAS_TABLE: ${self:service}-${self:provider.stage}-compras
  iam:
    role: arn:aws:iam::498917627164:role/LabRole

functions:
  crearCompra:
    handler: crearCompra.handler
    events:
      - http:
          path: /compras
          method: post
          cors: true

  obtenerCompras:
    handler: obtenerCompras.handler
    events:
      - http:
          path: /compras
          method: get
          cors: true

  modificarCompra:
    handler: modificarCompra.handler
    events:
      - http:
          path: /compras
          method: put
          cors: true

  eliminarCompra:
    handler: eliminarCompra.handler
    events:
      - http:
          path: /compras
          method: delete
          cors: true

  obtenerCompraById:
    handler: obtenerCompraById.handler
    events:
      - http:
          path: /compras/{id_compra}
          method: get
          cors: true

resources:
  Resources:
    ComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COMPRAS_TABLE}
        AttributeDefinitions:
          - AttributeName: id_usuario
            AttributeType: S
          - AttributeName: id_compra
            AttributeType: S
          - AttributeName: fecha_compra
            AttributeType: S   # Usado para el LSI
          - AttributeName: estado
            AttributeType: S   # Usado para el GSI
        KeySchema:
          - AttributeName: id_usuario
            KeyType: HASH
          - AttributeName: id_compra
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

        # Índice Secundario Local (LSI)
        LocalSecondaryIndexes:
          - IndexName: FechaCompraIndex
            KeySchema:
              - AttributeName: id_usuario
                KeyType: HASH
              - AttributeName: fecha_compra
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        # Índice Secundario Global (GSI)
        GlobalSecondaryIndexes:
          - IndexName: EstadoIndex
            KeySchema:
              - AttributeName: estado
                KeyType: HASH
              - AttributeName: id_compra
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
